//
// Generated by dtk
// Translation Unit: stb-data.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/JStudio/JStudio/stb-data.h"
#include "dolphin/types.h"

const s32 JStudio::stb::data::gauDataSize_TEParagraph_data[8] = {0x0, 0x1, 0x2, 0x4, 0x8, 0x10, 0x20, 0x40};
const BE(u32) JStudio::stb::data::ga4cSignature = 'STB\0'; // big-endian as in the file on the host
