//
// Generated by dtk
// Translation Unit: object-message.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/JStudio/JStudio_JMessage/object-message.h"
#include "dolphin/types.h"
#include "helpers/endian.h"

/* 8027A614-8027A64C       .text __ct__Q216JStudio_JMessage16TAdaptor_messageFPQ28JMessage8TControl */
JStudio_JMessage::TAdaptor_message::TAdaptor_message(JMessage::TControl* control)
    : JStudio::TAdaptor_message()
    , mControl(control)
{
}

/* 8027A64C-8027A6AC       .text __dt__Q216JStudio_JMessage16TAdaptor_messageFv */
JStudio_JMessage::TAdaptor_message::~TAdaptor_message() {}

/* 8027A6AC-8027A6EC       .text adaptor_do_MESSAGE__Q216JStudio_JMessage16TAdaptor_messageFQ37JStudio4data15TEOperationDataPCvUl */
void JStudio_JMessage::TAdaptor_message::adaptor_do_MESSAGE(JStudio::data::TEOperationData operation, const void* param_2, u32 param_3) {
    switch (operation) {
    case JStudio::data::TEOD_Unknown_19:
        // The message code is a big-endian u32 in the STB paragraph (BE(u32) is u32 on the
        // GameCube), as in Dusklight's jstudio_tAdaptor_message::adaptor_do_MESSAGE
        // (src/d/d_demo.cpp, CC0, ref/dusklight at 40457c6).
        mControl->setMessageCode(*(const BE(u32)*)param_2);
        break;
    default:
        break;
    }
}
