//
// Generated by dtk
// Translation Unit: J3DClusterLoader.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/J3DGraphLoader/J3DClusterLoader.h"
#include "JSystem/J3DGraphAnimator/J3DSkinDeform.h"
#include "m_Do/m_Do_printf.h"
#include "JSystem/JSupport/JSupport.h"
#include "JSystem/JUtility/JUTNameTab.h"

/* 802FB04C-802FB0E8       .text load__24J3DClusterLoaderDataBaseFPCv */
void* J3DClusterLoaderDataBase::load(const void* i_data) {
    const JUTDataFileHeader* fileHeader = (JUTDataFileHeader*)i_data;
    if (fileHeader->mMagic == 'J3D1' && fileHeader->mType == 'bls1') {
        J3DClusterLoader_v15 loader;
        return loader.load(i_data);
    } else if (fileHeader->mMagic == 'J3D2' && fileHeader->mType == 'bls2') {
        return NULL;
    }
    return NULL;
}

/* 802FB0E8-802FB104       .text __ct__20J3DClusterLoader_v15Fv */
J3DClusterLoader_v15::J3DClusterLoader_v15() {}

/* 802FB104-802FB160       .text __dt__20J3DClusterLoader_v15Fv */
J3DClusterLoader_v15::~J3DClusterLoader_v15() {}

/* 802FB160-802FB21C       .text load__20J3DClusterLoader_v15FPCv */
void* J3DClusterLoader_v15::load(const void* i_data) {
    mpDeformData = new J3DDeformData();
    mpDeformData->clear();

    const JUTDataFileHeader* fileHeader = (JUTDataFileHeader*)i_data;
    const JUTDataBlockHeader* block = &fileHeader->mFirstBlock;
    for (int i = 0; i < fileHeader->mBlockNum; i++) {
        switch (block->mType) {
        case 'CLS1':
            readCluster((J3DClusterBlock*)block);
            break;
        default:
            OSReport("Unknown data block\n");
            break;
        }
        block = (JUTDataBlockHeader*)((u8*)block + block->mSize);
    }

    return mpDeformData;
}

/* 802FB21C-802FB698       .text readCluster__20J3DClusterLoader_v15FPC15J3DClusterBlock */
#if TARGET_PC
// The CLS1 records as stored: big-endian, 32-bit offsets from the block where the host J3DCluster,
// J3DClusterKey and J3DClusterVertex hold pointers (and so are larger).
struct J3DClusterData {
    /* 0x00 */ BE(f32) mMaxAngle;
    /* 0x04 */ BE(f32) mMinAngle;
    /* 0x08 */ BE(u32) mClusterKey;
    /* 0x0C */ u8 mFlags;
    /* 0x0D */ u8 field_0xd[3];
    /* 0x10 */ BE(u16) mKeyNum;
    /* 0x12 */ BE(u16) mPosNum;
    /* 0x14 */ BE(u16) mNrmNum;
    /* 0x16 */ BE(u16) mClusterVertexNum;
    /* 0x18 */ BE(u32) mPosDstIdx;
    /* 0x1C */ BE(u32) mClusterVertex;
    /* 0x20 */ BE(u32) mDeformer;
};  // Size: 0x24

struct J3DClusterKeyData {
    /* 0x00 */ BE(u16) mPosNum;
    /* 0x02 */ BE(u16) mNrmNum;
    /* 0x04 */ BE(u32) mPosFlag;
    /* 0x08 */ BE(u32) mNrmFlag;
};  // Size: 0x0C

struct J3DClusterVertexData {
    /* 0x00 */ BE(u16) mNum;
    /* 0x04 */ BE(u32) mSrcIdx;
    /* 0x08 */ BE(u32) mDstIdx;
};  // Size: 0x0C

// The loader of the GameCube copies the records and relocates their offsets; on the host the
// records are converted into the host structs instead, with the same pointers. The index and
// position/normal arrays they point at stay in the file (big-endian; the deformer reads them,
// step 4.12).
void J3DClusterLoader_v15::readCluster(const J3DClusterBlock* block) {
    mpDeformData->mClusterNum = block->mClusterNum;
    mpDeformData->mClusterKeyNum = block->mClusterKeyNum;
    mpDeformData->mVtxPosNum = block->mVtxPosNum;
    mpDeformData->mVtxNrmNum = block->mVtxNrmNum;
    mpDeformData->mClusterVertexNum = block->mClusterVertexNum;

    if (block->mClusterName != 0) {
        mpDeformData->mClusterName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(block, block->mClusterName));
    } else {
        mpDeformData->mClusterName = NULL;
    }
    if (block->mClusterKeyName != 0) {
        mpDeformData->mClusterKeyName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(block, block->mClusterKeyName));
    } else {
        mpDeformData->mClusterKeyName = NULL;
    }

    mpDeformData->mVtxPos = JSUConvertOffsetToPtr<f32>(block, block->mVtxPos);
    mpDeformData->mVtxNrm = JSUConvertOffsetToPtr<f32>(block, block->mVtxNrm);

    const J3DClusterData* blockCluster = JSUConvertOffsetToPtr<J3DClusterData>(block, block->mClusterPointer);
    const J3DClusterKeyData* blockClusterKey = JSUConvertOffsetToPtr<J3DClusterKeyData>(block, block->mClusterKeyPointer);
    const J3DClusterVertexData* blockClusterVertex = JSUConvertOffsetToPtr<J3DClusterVertexData>(block, block->mClusterVertex);

    mpDeformData->mClusterKeyPointer = new J3DClusterKey[mpDeformData->getClusterKeyNum()];
    for (int i = 0; i < mpDeformData->getClusterKeyNum(); i++) {
        J3DClusterKey* clusterKey = &mpDeformData->mClusterKeyPointer[i];
        clusterKey->mPosNum = blockClusterKey[i].mPosNum;
        clusterKey->mNrmNum = blockClusterKey[i].mNrmNum;
        clusterKey->mPosFlag = JSUConvertOffsetToPtr<u16>(block, blockClusterKey[i].mPosFlag);
        clusterKey->mNrmFlag = JSUConvertOffsetToPtr<u16>(block, blockClusterKey[i].mNrmFlag);
    }

    mpDeformData->mClusterVertex = new J3DClusterVertex[mpDeformData->mClusterVertexNum];
    for (int i = 0; i < mpDeformData->mClusterVertexNum; i++) {
        J3DClusterVertex* clusterVertex = &mpDeformData->mClusterVertex[i];
        clusterVertex->mNum = blockClusterVertex[i].mNum;
        clusterVertex->mSrcIdx = JSUConvertOffsetToPtr<u16>(block, blockClusterVertex[i].mSrcIdx);
        clusterVertex->mDstIdx = JSUConvertOffsetToPtr<u16>(block, blockClusterVertex[i].mDstIdx);
    }

    mpDeformData->mClusterPointer = new J3DCluster[mpDeformData->getClusterNum()];
    for (int i = 0; i < mpDeformData->getClusterNum(); i++) {
        const J3DClusterData& data = blockCluster[i];
        J3DCluster* cluster = &mpDeformData->mClusterPointer[i];
        cluster->mMaxAngle = data.mMaxAngle;
        cluster->mMinAngle = data.mMinAngle;
        cluster->mFlags = data.mFlags;
        cluster->mKeyNum = data.mKeyNum;
        cluster->mPosNum = data.mPosNum;
        cluster->mNrmNum = data.mNrmNum;
        cluster->mClusterVertexNum = data.mClusterVertexNum;
        // The GameCube points mClusterKey at the file's key record (whose flag offsets it never
        // relocates); on the host it points at that record's converted copy (same counts, flag
        // pointers relocated). No BLS file is on the TWW disc.
        u32 keyIdx = ((u32)data.mClusterKey - (u32)block->mClusterKeyPointer) / sizeof(J3DClusterKeyData);
        cluster->mClusterKey = &mpDeformData->mClusterKeyPointer[keyIdx];
        cluster->mPosDstIdx = JSUConvertOffsetToPtr<u16>(block, data.mPosDstIdx);
        // As the GameCube computes it: the record's index, divided once more by the record size.
        u32 vertexIdx = ((u32)data.mClusterVertex - (u32)block->mClusterVertex) / sizeof(J3DClusterVertexData) /
                        sizeof(J3DClusterVertexData);
        cluster->mClusterVertex = &mpDeformData->mClusterVertex[vertexIdx];
        J3DDeformer* deformer = new J3DDeformer(mpDeformData);
        if (cluster->mNrmNum != 0) {
            deformer->field_0x0c = new f32[cluster->mNrmNum * 3];
        } else {
            deformer->field_0x0c = NULL;
        }
        deformer->mFlags = cluster->mFlags;
        deformer->mWeightList = new f32[cluster->mKeyNum];
        cluster->setDeformer(deformer);
    }
}
#else
void J3DClusterLoader_v15::readCluster(const J3DClusterBlock* block) {
    mpDeformData->mClusterNum = block->mClusterNum;
    mpDeformData->mClusterKeyNum = block->mClusterKeyNum;
    mpDeformData->mVtxPosNum = block->mVtxPosNum;
    mpDeformData->mVtxNrmNum = block->mVtxNrmNum;
    mpDeformData->mClusterVertexNum = block->mClusterVertexNum;

    if (block->mClusterName != NULL) {
        mpDeformData->mClusterName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(block, block->mClusterName));
    } else {
        mpDeformData->mClusterName = NULL;
    }
    if (block->mClusterKeyName != NULL) {
        mpDeformData->mClusterKeyName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(block, block->mClusterKeyName));
    } else {
        mpDeformData->mClusterKeyName = NULL;
    }

    mpDeformData->mVtxPos = JSUConvertOffsetToPtr<f32>(block, block->mVtxPos);
    mpDeformData->mVtxNrm = JSUConvertOffsetToPtr<f32>(block, block->mVtxNrm);

    mpDeformData->mClusterPointer = new J3DCluster[mpDeformData->getClusterNum()];
    J3DCluster* blockCluster = JSUConvertOffsetToPtr<J3DCluster>(block, block->mClusterPointer);
    for (int i = 0; i < mpDeformData->getClusterNum(); i++) {
        mpDeformData->mClusterPointer[i] = blockCluster[i];
    }

    mpDeformData->mClusterKeyPointer = new J3DClusterKey[mpDeformData->getClusterKeyNum()];
    J3DClusterKey* blockClusterKey = JSUConvertOffsetToPtr<J3DClusterKey>(block, block->mClusterKeyPointer);
    for (int i = 0; i < mpDeformData->getClusterKeyNum(); i++) {
        mpDeformData->mClusterKeyPointer[i] = blockClusterKey[i];
    }

    mpDeformData->mClusterVertex = new J3DClusterVertex[mpDeformData->mClusterVertexNum];
    J3DClusterVertex* blockClusterVertex = JSUConvertOffsetToPtr<J3DClusterVertex>(block, block->mClusterVertex);
    for (int i = 0; i < mpDeformData->mClusterVertexNum; i++) {
        mpDeformData->mClusterVertex[i] = blockClusterVertex[i];
    }

    for (int i = 0; i < mpDeformData->getClusterNum(); i++) {
        J3DCluster* cluster = &mpDeformData->mClusterPointer[i];
        cluster->mClusterKey = JSUConvertOffsetToPtr<J3DClusterKey>(block, cluster->mClusterKey);
        cluster->mPosDstIdx = JSUConvertOffsetToPtr<u16>(block, cluster->mPosDstIdx);
        J3DClusterVertex* clusterVertex = JSUConvertOffsetToPtr<J3DClusterVertex>(block, cluster->mClusterVertex);
        u32 vertexIdx = (clusterVertex - blockClusterVertex) / sizeof(J3DClusterVertex);
        cluster->mClusterVertex = &mpDeformData->mClusterVertex[vertexIdx];
        J3DDeformer* deformer = new J3DDeformer(mpDeformData);
        if (cluster->mNrmNum != 0) {
            deformer->field_0x0c = new f32[cluster->mNrmNum * 3];
        } else {
            deformer->field_0x0c = NULL;
        }
        deformer->mFlags = cluster->mFlags;
        deformer->mWeightList = new f32[cluster->mKeyNum];
        cluster->setDeformer(deformer);
    }

    for (int i = 0; i < mpDeformData->getClusterKeyNum(); i++) {
        J3DClusterKey* clusterKey = &mpDeformData->mClusterKeyPointer[i];
        clusterKey->mPosFlag = JSUConvertOffsetToPtr<u16>(block, clusterKey->mPosFlag);
        clusterKey->mNrmFlag = JSUConvertOffsetToPtr<u16>(block, clusterKey->mNrmFlag);
    }

    for (int i = 0; i < mpDeformData->mClusterVertexNum; i++) {
        J3DClusterVertex* clusterVertex = &mpDeformData->mClusterVertex[i];
        clusterVertex->mSrcIdx = JSUConvertOffsetToPtr<u16>(block, clusterVertex->mSrcIdx);
        clusterVertex->mDstIdx = JSUConvertOffsetToPtr<u16>(block, clusterVertex->mDstIdx);
    }
}
#endif
