//
// Generated by dtk
// Translation Unit: J3DShape.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/J3DGraphBase/J3DShape.h"
#include "JSystem/J3DGraphBase/J3DPacket.h"
#include "JSystem/J3DGraphBase/J3DSys.h"
#include "JSystem/J3DGraphBase/J3DVertex.h"
#include "JSystem/J3DGraphBase/J3DGD.h"
#include "dolphin/gd/GDBase.h"
#include "dolphin/gd/GDGeometry.h"
#include "dolphin/types.h"

/* 802DD18C-802DD1FC       .text initialize__8J3DShapeFv */
void J3DShape::initialize() {
    mMaterial = NULL;
    mIndex = -1;
    mMtxGroupNum = 0;
    mFlags = 0;
    mRadius = 0.0f;
    mMin.x = 0.0f;
    mMin.y = 0.0f;
    mMin.z = 0.0f;
    mMax.x = 0.0f;
    mMax.y = 0.0f;
    mMax.z = 0.0f;
    mVtxDesc = NULL;
    mShapeMtx = NULL;
    mShapeDraw = NULL;
    mVertexData = NULL;
    mDrawMtxData = NULL;
    mScaleFlagArray = NULL;
    mDrawMtx = NULL;
    mNrmMtx = NULL;
    mCurrentViewNo = &j3dDefaultViewNo;
    mHasNBT = false;
    mHasPNMTXIdx = false;
}

/* 802DD1FC-802DD27C       .text calcNBTScale__8J3DShapeFRC3VecPA3_A3_fPA3_A3_f */
void J3DShape::calcNBTScale(Vec const& scale, Mtx33* pSrc, Mtx33* pDst) {
    for (u16 i = 0; i < getMtxGroupNum(); i++)
        getShapeMtx(i)->calcNBTScale(scale, pSrc, pDst);
}

/* 802DD27C-802DD2F0       .text countBumpMtxNum__8J3DShapeCFv */
u32 J3DShape::countBumpMtxNum() const {
    u32 num = 0;
    for (u16 i = 0; i < getMtxGroupNum(); i++)
        num += getShapeMtx(i)->getUseMtxNum();
    return num;
}

/* 802DD2F0-802DD308       .text J3DLoadCPCmd__FUcUl */
void J3DLoadCPCmd(u8 cmd, u32 param) {
#if TARGET_PC
    // No write-gather pipe on the host: Aurora's GXCmd1u* feed its FIFO (in decomp-header mode they
    // are the inline GXFIFO writes of dolphin/gx/GX.h). Same bytes, same order.
    GXCmd1u8(GX_CMD_LOAD_CP_REG);
    GXCmd1u8(cmd);
    GXCmd1u32(param);
#else
    GXFIFO.u8 = GX_CMD_LOAD_CP_REG;
    GXFIFO.u8 = cmd;
    GXFIFO.u32 = param;
#endif
}

#if TARGET_PC
// Aurora has no CP_REG_ARRAYBASE (it logs "not supported" and ignores the write: a 32-bit
// physical address cannot hold a host pointer). Its replacement, GX_AURORA_LOAD_ARRAYBASE, takes
// the 64-bit pointer, the array's size in bytes and its byte order, the same command
// GDSetArraySized puts in the shape's VCD/VAT list (after Dusklight's J3DShape.cpp; the stride
// stays the one that list set, as on the GameCube).
static void J3DLoadArrayBasePtr(GXAttr attr, void* data, u32 size) {
    u32 idx = (attr == GX_VA_NBT) ? 1 : (attr - GX_VA_POS);
    const u64 addr = (u64)(uintptr_t)data;
    GXCmd1u8(GX_AURORA);
    GXCmd1u16(GX_AURORA_LOAD_ARRAYBASE + idx);
    GXCmd1u32((u32)(addr >> 32));
    GXCmd1u32((u32)addr);
    GXCmd1u32(size);
    // Every array a J3DVertexBuffer hands out is in the console's byte order (big-endian): the
    // model's VTX1 arrays as on the disc, and the CPU deformers' output arrays, which keep the
    // layout of the arrays they are computed from.
    GXCmd1u8(0);
}

// The size of the vertex array `data` points at: the model's own VTX1 array is sized as in the
// shape's VCD/VAT list (so Aurora sees the same array and keeps its cached upload); any other
// array (a deformer's output, allocated for `num` entries) is `num` entries of `stride` bytes.
static u32 J3DVtxArraySize(const J3DVertexData* vtxData, const void* data, const void* modelArray,
                           u32 num, u32 stride) {
    if (data == NULL)
        return 0;
    if (data == modelArray)
        return vtxData->getVtxArraySize(data);
    return num * stride;
}
#else
/* 802DD308-802DD344       .text J3DLoadArrayBasePtr__F7_GXAttrPv */
static void J3DLoadArrayBasePtr(GXAttr attr, void* data) {
    u32 idx = (attr == GX_VA_NBT) ? 1 : (attr - GX_VA_POS);
    J3DLoadCPCmd(0xA0 + idx, ((u32)data & 0x7FFFFFFF));
}
#endif

/* 802DD344-802DD3B4       .text loadVtxArray__8J3DShapeCFv */
void J3DShape::loadVtxArray() const {
#if TARGET_PC
    void* pos = j3dSys.getVtxPos();
    J3DLoadArrayBasePtr(GX_VA_POS, pos,
                        J3DVtxArraySize(mVertexData, pos, mVertexData->getVtxPosArray(), mVertexData->getVtxNum(),
                                        mVertexData->getVtxPosType() == GX_F32 ? 0x0C : 0x06));
    if (!mHasNBT) {
        void* nrm = j3dSys.getVtxNrm();
        J3DLoadArrayBasePtr(GX_VA_NRM, nrm,
                            J3DVtxArraySize(mVertexData, nrm, mVertexData->getVtxNrmArray(), mVertexData->getNrmNum(),
                                            mVertexData->getVtxNrmType() == GX_F32 ? 0x0C : 0x06));
    }
    void* col = j3dSys.getVtxCol();
    J3DLoadArrayBasePtr(GX_VA_CLR0, col,
                        J3DVtxArraySize(mVertexData, col, mVertexData->getVtxColorArray(0), mVertexData->getColNum(),
                                        sizeof(GXColor)));
#else
    J3DLoadArrayBasePtr(GX_VA_POS, j3dSys.getVtxPos());
    if (!mHasNBT) {
        J3DLoadArrayBasePtr(GX_VA_NRM, j3dSys.getVtxNrm());
    }
    J3DLoadArrayBasePtr(GX_VA_CLR0, j3dSys.getVtxCol());
#endif
}

/* 802DD3B4-802DD3F0       .text isSameVcdVatCmd__8J3DShapeFP8J3DShape */
bool J3DShape::isSameVcdVatCmd(J3DShape* other) {
    u8* a = other->mVcdVatCmd;
    u8* b = mVcdVatCmd;
    for (u32 i = 0; i < kVcdVatDLSize; i++)
        if (a[i] != b[i])
            return false;
    return true;
}

/* 802DD3F0-802DD6B8       .text makeVtxArrayCmd__8J3DShapeFv */
void J3DShape::makeVtxArrayCmd() {
    GXVtxAttrFmtList* vtxAttr = mVertexData->getVtxAttrFmtList();

    u8 stride[0x0C];
    void* array[0x0C];
    for (u32 i = 0; i < 0x0C; i++) {
        stride[i] = 0;
        array[i] = 0;
    }

    for (; vtxAttr->attr != GX_VA_NULL; vtxAttr++) {
        switch (vtxAttr->attr) {
        case GX_VA_POS: {
            if (vtxAttr->type == GX_F32)
                stride[vtxAttr->attr - GX_VA_POS] = 0x0C;
            else
                stride[vtxAttr->attr - GX_VA_POS] = 0x06;
            array[vtxAttr->attr - GX_VA_POS] = mVertexData->getVtxPosArray();
            mVertexData->setVtxPosFrac(vtxAttr->frac);
            mVertexData->setVtxPosType((GXCompType)vtxAttr->type);
        } break;
        case GX_VA_NRM: {
            if (vtxAttr->type == GX_F32)
                stride[vtxAttr->attr - GX_VA_POS] = 0x0C;
            else
                stride[vtxAttr->attr - GX_VA_POS] = 0x06;
            array[vtxAttr->attr - GX_VA_POS] = mVertexData->getVtxNrmArray();
            mVertexData->setVtxNrmFrac(vtxAttr->frac);
            mVertexData->setVtxNrmType((GXCompType)vtxAttr->type);
        } break;
        case GX_VA_CLR0:
        case GX_VA_CLR1: {
            stride[vtxAttr->attr - GX_VA_POS] = 0x04;
            array[vtxAttr->attr - GX_VA_POS] =
                mVertexData->getVtxColorArray(vtxAttr->attr - GX_VA_CLR0);
        } break;
        case GX_VA_TEX0:
        case GX_VA_TEX1:
        case GX_VA_TEX2:
        case GX_VA_TEX3:
        case GX_VA_TEX4:
        case GX_VA_TEX5:
        case GX_VA_TEX6:
        case GX_VA_TEX7: {
            if (vtxAttr->type == GX_F32)
                stride[vtxAttr->attr - GX_VA_POS] = 0x08;
            else
                stride[vtxAttr->attr - GX_VA_POS] = 0x04;
            array[vtxAttr->attr - GX_VA_POS] = mVertexData->getVtxTexCoordArray(vtxAttr->attr - GX_VA_TEX0);
        } break;
        default:
            break;
        }
    }

    GXVtxDescList* vtxDesc = mVtxDesc;
    mHasPNMTXIdx = false;
    for (; vtxDesc->attr != GX_VA_NULL; vtxDesc++) {
        if (vtxDesc->attr == GX_VA_NBT && vtxDesc->type != GX_NONE) {
            mHasNBT = true;
            stride[GX_VA_NRM - GX_VA_POS] *= 3;
            array[GX_VA_NRM - GX_VA_POS] = mVertexData->getVtxNBTArray();
        }

        if (vtxDesc->attr == GX_VA_PNMTXIDX && vtxDesc->type != GX_NONE) {
            mHasPNMTXIdx = true;
        }
    }

#if TARGET_PC
    // Aurora has no 32-bit array base (GDSetArray/GDSetArrayRaw are fatal there): its
    // GDSetArraySized records the host pointer, the array's size and its byte order. The model's
    // vertex arrays stay big-endian as on the disc (le = false).
    for (s32 i = 0; i < 0x0C; i++) {
        if (array[i] != 0)
            GDSetArraySized((GXAttr)(i + GX_VA_POS), array[i], mVertexData->getVtxArraySize(array[i]), stride[i], false);
        else
            GDSetArraySized((GXAttr)(i + GX_VA_POS), NULL, 0, stride[i], false);
    }
#else
    for (s32 i = 0; i < 0x0C; i++) {
        if (array[i] != 0)
            GDSetArray((GXAttr)(i + GX_VA_POS), array[i], stride[i]);
        else
            GDSetArrayRaw((GXAttr)(i + GX_VA_POS), NULL, stride[i]);
    }
#endif
}

/* 802DD6B8-802DD72C       .text makeVcdVatCmd__8J3DShapeFv */
void J3DShape::makeVcdVatCmd() {
    GDLObj gdl_obj;
    GDInitGDLObj(&gdl_obj, mVcdVatCmd, kVcdVatDLSize);
    GDSetCurrent(&gdl_obj);
    GDSetVtxDescv(mVtxDesc);
    makeVtxArrayCmd();
    J3DGDSetVtxAttrFmtv(GX_VTXFMT0, mVertexData->getVtxAttrFmtList(), mHasNBT);
    GDPadCurr32();
    GDFlushCurrToMem();
    GDSetCurrent(NULL);
}

void* J3DShape::sOldVcdVatCmd;

/* 802DD72C-802DD7CC       .text loadPreDrawSetting__8J3DShapeCFv */
void J3DShape::loadPreDrawSetting() const {
    if (sOldVcdVatCmd != mVcdVatCmd) {
        GXCallDisplayList(mVcdVatCmd, kVcdVatDLSize);
        sOldVcdVatCmd = mVcdVatCmd;
    }

    mCurrentMtx.load();
}

u8 J3DShape::sEnvelopeFlag;

/* 802DD7CC-802DD874       .text setArrayAndBindPipeline__8J3DShapeCFv */
void J3DShape::setArrayAndBindPipeline() const {
    J3DShapeMtx::setCurrentPipeline(getPipeline());
    loadVtxArray();
    j3dSys.setModelDrawMtx(mDrawMtx[*mCurrentViewNo]);
    j3dSys.setModelNrmMtx(mNrmMtx[*mCurrentViewNo]);
    J3DShapeMtx::sCurrentScaleFlag = mScaleFlagArray;
    J3DShapeMtx::sNBTFlag = mHasNBT;
    J3DShape::sEnvelopeFlag = mHasPNMTXIdx;
}

/* 802DD874-802DD9FC       .text drawFast__8J3DShapeCFv */
void J3DShape::drawFast() const {
    if (sOldVcdVatCmd != mVcdVatCmd) {
        GXCallDisplayList(mVcdVatCmd, kVcdVatDLSize);
        sOldVcdVatCmd = mVcdVatCmd;
    }

    if (sEnvelopeFlag != 0 && !mHasPNMTXIdx)
        mCurrentMtx.load();

    setArrayAndBindPipeline();
    if (!checkFlag(J3DShpFlag_NoMtx)) {
        for (u16 i = 0; i < getMtxGroupNum(); i++) {
            if (getShapeMtx(i) != NULL)
                getShapeMtx(i)->load();
            if (getShapeDraw(i) != NULL)
                getShapeDraw(i)->draw();
        }
    } else {
        J3DFifoLoadPosMtxImm(*j3dSys.getShapePacket()->getBaseMtxPtr(), GX_PNMTX0);
        J3DFifoLoadNrmMtxImm(*j3dSys.getShapePacket()->getBaseMtxPtr(), GX_PNMTX0);
        for (u16 i = 0; i < getMtxGroupNum(); i++)
            if (getShapeDraw(i) != NULL)
                getShapeDraw(i)->draw();
    }
}

/* 802DD9FC-802DDA44       .text draw__8J3DShapeCFv */
void J3DShape::draw() const {
    sOldVcdVatCmd = NULL;
    loadPreDrawSetting();
    drawFast();
}

/* 802DDA44-802DDAC8       .text simpleDraw__8J3DShapeCFv */
void J3DShape::simpleDraw() const {
    resetVcdVatCache();
    loadPreDrawSetting();
    J3DShapeMtx::setCurrentPipeline(getPipeline());
    loadVtxArray();
    for (u16 i = 0; i < getMtxGroupNum(); i++) {
        if (getShapeDraw(i) != NULL) {
            getShapeDraw(i)->draw();
        }
    }
}

/* 802DDAC8-802DDBC4       .text simpleDrawCache__8J3DShapeCFv */
void J3DShape::simpleDrawCache() const {
    if (sOldVcdVatCmd != mVcdVatCmd) {
        GXCallDisplayList(mVcdVatCmd, kVcdVatDLSize);
        sOldVcdVatCmd = mVcdVatCmd;
    }

    if (sEnvelopeFlag != 0 && !mHasPNMTXIdx)
        mCurrentMtx.load();

    loadVtxArray();
    for (u16 i = 0; i < getMtxGroupNum(); i++)
        if (getShapeDraw(i) != NULL)
            getShapeDraw(i)->draw();
}
