//
// Generated by dtk
// Translation Unit: c_API_graphic.cpp
//

#include "SSystem/SComponent/c_API_graphic.h"
#include "SSystem/SComponent/c_API.h"
#include "dolphin/types.h"
#if TARGET_PC
#include "pc/pc_harness.h"
#endif

/* 8024135C-8024138C       .text cAPIGph_Painter__Fv */
void cAPIGph_Painter(void) {
#if TARGET_PC
    // Step 6.7 (pc_frame.cpp): mDoGph_Painter's GX encode, a phase of TWW_PERF / TWW_PERF_EVERY.
    pc_perf_begin(PC_PERF_PAINTER);
    g_cAPI_Interface.mpPainter();
    pc_perf_end(PC_PERF_PAINTER);
#else
    g_cAPI_Interface.mpPainter();
#endif
}

/* 8024138C-802413BC       .text cAPIGph_BeforeOfDraw__Fv */
void cAPIGph_BeforeOfDraw(void) {
    g_cAPI_Interface.mpBeforeOfDraw();
}

/* 802413BC-802413EC       .text cAPIGph_AfterOfDraw__Fv */
void cAPIGph_AfterOfDraw(void) {
    g_cAPI_Interface.mpAfterOfDraw();
}
